### PR TITLE
Update python version to 3.11 - fixed

### PR DESCRIPTION
**Pull request by rickythefox**
Based on #53 . Fixes the CI issues.

closes #53

### CODE REVIEW

**Comment by rickythefox** [comment]
@mesaugat CI build is passing now

**Comment by dataders** [comment]
I know that this package isn't under active development, but I really think this PR is worth merging and including in a new release because Python 3.11:
1. is now the default version that a user gets when installing Python -- without 3.11 support, `pyodbc` does not work out of the box
2. offers significant speed up opportunities

**Comment by mesaugat** [comment]
@rickythefox Hey thanks for the updating the base image. This was needed. I hope to get this sorted and published soon.

**Review by mesaugat — APPROVED** [review]

**Comment by mesaugat** [comment]
Released in v2.0.0 --> https://github.com/laudio/pyodbc/releases/tag/2.0.0

Please report if you find any issues.

**Pull request merged**
