### PR TITLE
Bump pyodbc to 4.0.30

### PR DESCRIPTION
**Pull request by kabirbaidhya**
- Bump pyodbc to 4.0.30.
- See the changelog here --> https://github.com/mkleehammer/pyodbc/releases

### CODE REVIEW

**Comment by mesaugat** [comment]
@kabirbaidhya There's no version with version number `4.0.30`.

```
ERROR: Could not find a version that satisfies the requirement pyodbc==4.0.30 (from -r requirements.txt (line 1)) (from versions: 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.1.7, 2.1.8, 2.1.9, 2.1.10, 2.1.11, 3.0.3, 3.0.6, 3.0.7, 3.0.8, 3.0.9, 3.0.10, 3.1.1, 4.0.1, 4.0.2, 4.0.3, 4.0.5, 4.0.6, 4.0.7, 4.0.8, 4.0.9, 4.0.10, 4.0.11, 4.0.12, 4.0.13, 4.0.14, 4.0.15, 4.0.16, 4.0.17, 4.0.18, 4.0.19, 4.0.20, 4.0.21, 4.0.22, 4.0.23, 4.0.24, 4.0.25, 4.0.26, 4.0.27, 4.0.28, 4.0.30b1)
```

**Comment by SafalPandey** [comment]
@mesaugat Looks like `4.0.30b1` is available. @kabirbaidhya Was this the intended version?

**Comment by mesaugat** [comment]
@SafalPandey Yes `4.0.31b` is available and the error has listed that version.

**Review by cham11ng — APPROVED** [review]

**Comment by kabirbaidhya** [comment]
@mesaugat @SafalPandey This was the intended version - https://github.com/mkleehammer/pyodbc/tree/4.0.30.

But I was not aware that they pushed the version to GitHub but not pypi :smile:. Let's keep this PR open then. `4.0.30b1` looks like a pre-release, I'd prefer to wait until it's out of beta before we bump.

**Pull request merged**
